### ISSUE TITLE
Link to Public Domain Unit is broken 

### ISSUE THREAD

**Issue by Stephen-Gates** [creativecommons/cc-cert-map#32]
Link [here](https://github.com/creativecommons/cc-cert-core/blame/master/contents/copyright/exceptions-limitations.md#L19) needs to go up a directory level.

**Comment by cogdog** [comment]
Local link on public domain from https://github.com/creativecommons/cc-cert-core/blob/master/contents/copyright/exceptions-limitations.md seems to work as expected leading to https://github.com/creativecommons/cc-cert-core/blob/master/contents/copyright/public-domain.md

I've been hesitant to include inter unit links since the published versions have navigation built in, we do not expect ppl to access directly to this repo.
